### ISSUE TITLE
Rewrite eq. (3) and clarify the passage explaining it

### ISSUE THREAD

**Issue by labarba** [barbagroup/inexact-gmres#22]
Equation 3 is missing a term of 1/2 added to the diagonal of the A matrix when you have a Neumann boundary condition (second case shown).

With a Dirichlet boundary condition (first case shown), the 1/2 term appears on the right-hand side (which is not mentioned in the sentence right after Eq. 3). This section therefore gives an incomplete explanation of the math.

The equation can be rewritten as follows:

![latex-image-2](https://cloud.githubusercontent.com/assets/4800109/19536194/e8183bbe-9618-11e6-9339-6dd855abd185.png)

**Comment by tingyu66** [comment]
fixed by fc8a768
